# Generated by Django 4.2.19 on 2025-05-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='pic',
            field=models.ImageField(default='recipes/no_picture.jpg', upload_to='recipes/'),
        ),
    ]
