# Generated by Django 4.2.19 on 2025-06-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipes_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
